#include "device_registers.h"
#include "pin_mux.h"
#include "board.h"

pin_settings_config_t g_pin_mux_InitConfigArr[NUM_OF_CONFIGURED_PINS] = 
{
    /* Port A block settings */
	{
		.base              =  AUX_5V_EN_PORT,
		.pinPortIdx        =  AUX_5V_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  AUX_5V_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  AUX_CURRENT_SNS_PORT,
		.pinPortIdx        =  AUX_CURRENT_SNS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  AUX_CURRENT_SNS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  S32K_DBG_RX_PORT,
		.pinPortIdx        =  S32K_DBG_RX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT6,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX_S32K_RX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  S32K_DBG_TX_PORT,
		.pinPortIdx        =  S32K_DBG_TX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT6,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX_S32K_TX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  LEFT_IND_IO_PORT,
		.pinPortIdx        =  LEFT_IND_IO_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LEFT_IND_IO_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  RTC_CLK_HZ_PORT,
		.pinPortIdx        =  RTC_CLK_HZ_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT4,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  RTC_CLK_HZ_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  IMX_S32K_RX_PORT,
		.pinPortIdx        =  IMX_S32K_RX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT2,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX_S32K_RX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  IMX_S32K_TX_PORT,
		.pinPortIdx        =  IMX_S32K_TX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT2,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX_S32K_TX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  RTC_IRQ_PORT,
		.pinPortIdx        =  RTC_IRQ_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_INT_FALLING_EDGE,
		.clearIntFlag      =  true,
		.gpioBase          =  RTC_IRQ_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
        {
		.base              =  BMS_CAN_RXD_PORT,
		.pinPortIdx        =  BMS_CAN_RXD_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT3,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  BMS_CAN_RXD_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  BMS_CAN_TXD_PORT,
		.pinPortIdx        =  BMS_CAN_TXD_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT3,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  BMS_CAN_TXD_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  SHUTDOWN_MCU_N_PORT,
		.pinPortIdx        =  SHUTDOWN_MCU_N_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  SHUTDOWN_MCU_N_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  USB_VBUS_CTL_PORT,
		.pinPortIdx        =  USB_VBUS_CTL_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  USB_VBUS_CTL_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  VBAT_EN1_PORT,
		.pinPortIdx        =  VBAT_EN1_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  VBAT_EN1_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
        .base              =  REAR_BRAKE_LED_EN_PORT,
		.pinPortIdx        =  REAR_BRAKE_LED_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  REAR_BRAKE_LED_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  KEY_WAKE_SIG_PORT,
		.pinPortIdx        =  KEY_WAKE_SIG_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_INT_EITHER_EDGE,
		.clearIntFlag      =  true,
		.gpioBase          =  KEY_WAKE_SIG_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  WAKEUP_IN_MCU_PORT,
		.pinPortIdx        =  WAKEUP_IN_MCU_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  WAKEUP_IN_MCU_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  MOTOR_CAN_TX_PORT,
		.pinPortIdx        =  MOTOR_CAN_TX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MOTOR_CAN_TX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  MOTOR_CAN_RX_PORT,
		.pinPortIdx        =  MOTOR_CAN_RX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MOTOR_CAN_RX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  RESET_MCU_PORT,
		.pinPortIdx        =  RESET_MCU_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  RESET_MCU_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  IMU_CS_PORT,
		.pinPortIdx        =  IMU_CS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMU_CS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  HORN_EN_PORT,
		.pinPortIdx        =  HORN_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  HORN_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    
    /* Port B block settings */
    {
		.base              =  SWIF_CS_PORT,
		.pinPortIdx        =  SWIF_CS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  SWIF_CS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  SWIF_SI_PORT,
		.pinPortIdx        =  SWIF_SI_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT3,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  SWIF_SI_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  SWIF_CLK_PORT,
		.pinPortIdx        =  SWIF_CLK_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT3,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  SWIF_CLK_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  SWIF_SO_PORT,
		.pinPortIdx        =  SWIF_SO_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT3,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  SWIF_SO_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  MII_RMII_MDIO_PORT,
		.pinPortIdx        =  MII_RMII_MDIO_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
        /*.direction       =  GPIO_OUTPUT_DIRECTION,*/
		.initValue         =  0U,
	},
	{
		.base              =  MII_RMII_MDC_PORT,
		.pinPortIdx        =  MII_RMII_MDC_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT7,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
        /*.direction       =  GPIO_OUTPUT_DIRECTION,*/
		.initValue         =  0U,
	},
	{
		.base              =  ABS_OFF_MC_PORT,
		.pinPortIdx        =  ABS_OFF_MC_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ABS_OFF_MC_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  ETH_SW_RST_PORT,
		.pinPortIdx        =  ETH_SW_RST_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ETH_SW_RST_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  TACHY_MC_PORT,
		.pinPortIdx        =  TACHY_MC_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT2,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  TACHY_MC_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  NETWRK_STAT_PORT,
		.pinPortIdx        =  NETWRK_STAT_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NETWRK_STAT_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  DBA_CAN_RX_PORT,
		.pinPortIdx        =  DBA_CAN_RX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT4,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  DBA_CAN_RX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  DBA_CAN_TX_PORT,
		.pinPortIdx        =  DBA_CAN_TX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT4,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  DBA_CAN_TX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  IMU_SCL_PORT,
		.pinPortIdx        =  IMU_SCL_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT3,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMU_SCL_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  IMU_SDO_PORT,
		.pinPortIdx        =  IMU_SDO_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT3,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMU_SDO_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  IMU_SDI_PORT,
		.pinPortIdx        =  IMU_SDI_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT3,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMU_SDI_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  PAC9129_IRQ_PORT,
		.pinPortIdx        =  PAC9129_IRQ_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  PAC9129_IRQ_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
        {
		.base              =  HORN_VCC_EN_PORT,
		.pinPortIdx        =  HORN_VCC_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  HORN_VCC_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  SWIF_AMUX_PORT,
		.pinPortIdx        =  SWIF_AMUX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  SWIF_AMUX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_UNSPECIFIED_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  REV_EN_PORT,
		.pinPortIdx        =  REV_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  REV_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  HORN_IS_PORT,
		.pinPortIdx        =  HORN_IS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  HORN_IS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_UNSPECIFIED_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  DRL_TL_IS_PORT,
		.pinPortIdx        =  DRL_TL_IS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  DRL_TL_IS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_UNSPECIFIED_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  DEN_PORT,
		.pinPortIdx        =  DEN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  DEN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  ENET_MOSI_PORT,
		.pinPortIdx        =  ENET_MOSI_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ENET_MOSI_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  ENET_MISO_PORT,
		.pinPortIdx        =  ENET_MISO_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ENET_MISO_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  SWIF_WAKE_UP_PORT,
		.pinPortIdx        =  SWIF_WAKE_UP_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  SWIF_WAKE_UP_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    
    /* Port C block settings */
	{
		.base              =  MII_RMII_RX1_PORT,
		.pinPortIdx        =  MII_RMII_RX1_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT4,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
	},
	{
		.base              =  MII_RMII_RX0_PORT,
		.pinPortIdx        =  MII_RMII_RX0_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
	},
	{
		.base              =  MII_RMII_TXD0_PORT,
		.pinPortIdx        =  MII_RMII_TXD0_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
	},
        {
		.base              =  ENET_CS_PORT,
		.pinPortIdx        =  ENET_CS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ENET_CS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  LTE_TX_PORT,
		.pinPortIdx        =  LTE_TX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT2,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LTE_TX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  LTC_RX_PORT,
		.pinPortIdx        =  LTC_RX_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT2,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LTC_RX_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  MODE_GPIO_SW2_PORT,
		.pinPortIdx        =  MODE_GPIO_SW2_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MODE_GPIO_SW2_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  HIGH_BEAM_PORT,
		.pinPortIdx        =  HIGH_BEAM_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  HIGH_BEAM_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  IMX6_PMIC_EN_PORT,
		.pinPortIdx        =  IMX6_PMIC_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX6_PMIC_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  MODE_GPIO_SW_PORT,
		.pinPortIdx        =  MODE_GPIO_SW_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MODE_GPIO_SW_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  DRL_LED_EN_PORT,
		.pinPortIdx        =  DRL_LED_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  DRL_LED_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  SWIF_IRQ_PORT,
		.pinPortIdx        =  SWIF_IRQ_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_INT_FALLING_EDGE,
		.clearIntFlag      =  true,
		.gpioBase          =  SWIF_IRQ_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  BR_NP_IS_PORT,
		.pinPortIdx        =  BR_NP_IS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  BR_NP_IS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_UNSPECIFIED_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  HL_IS_PORT,
		.pinPortIdx        =  HL_IS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  HL_IS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_UNSPECIFIED_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  MII_RMII_RX_ER_PORT,
		.pinPortIdx        =  MII_RMII_RX_ER_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
	},
	{
		.base              =  MII_RMII_RX_DV_PORT,
		.pinPortIdx        =  MII_RMII_RX_DV_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
	},
    {
		.base              =  TAIL_LAMP_EN_PORT,
		.pinPortIdx        =  TAIL_LAMP_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  TAIL_LAMP_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  AUX_EN_PORT,
		.pinPortIdx        =  AUX_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  AUX_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  THRT_VDD_MONIT_PORT,
		.pinPortIdx        =  THRT_VDD_MONIT_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  THRT_VDD_MONIT_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  MAIN_VDC_MONIT_PORT,
		.pinPortIdx        =  MAIN_VDC_MONIT_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MAIN_VDC_MONIT_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  RIGHT_IND_IO_PORT,
		.pinPortIdx        =  RIGHT_IND_IO_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  RIGHT_IND_IO_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  PG_4G_PORT,
		.pinPortIdx        =  PG_4G_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  PG_4G_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  PG_5V_PORT,
		.pinPortIdx        =  PG_5V_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  PG_5V_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
    
    /* Port D block settings */
#ifdef USE_ETM_TRACE_DBG
    {
		.base              =  ETM_TRACE_D0_PORT,
		.pinPortIdx        =  ETM_TRACE_D0_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ETM_TRACE_D0_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  ETM_TRACE_D2_PORT,
		.pinPortIdx        =  ETM_TRACE_D2_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ETM_TRACE_D2_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  ETM_TRACE_D3_PORT,
		.pinPortIdx        =  ETM_TRACE_D3_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ETM_TRACE_D3_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
#endif /* USE_ETM_TRACE_DBG */
    {
		.base              =  LTE_IRQ_PORT,
		.pinPortIdx        =  LTE_IRQ_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LTE_IRQ_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  THROTTLE1_PORT,
		.pinPortIdx        =  THROTTLE1_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  THROTTLE1_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_UNSPECIFIED_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  DBA_CAN_ERR_PORT,
		.pinPortIdx        =  DBA_CAN_ERR_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  DBA_CAN_ERR_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  DBA_CAN_EN_PORT,
		.pinPortIdx        =  DBA_CAN_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  DBA_CAN_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},	
	{
		.base              =  MODE1_EN_PORT,
		.pinPortIdx        =  MODE1_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MODE1_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  IMX6_RESET_PORT,
		.pinPortIdx        =  IMX6_RESET_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX6_RESET_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
        {
		.base              =  MII_RMII_TXD1_PORT,
		.pinPortIdx        =  MII_RMII_TXD1_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
	},
	{
		.base              =  MOTOR_CON_ON_OFF_PORT,
		.pinPortIdx        =  MOTOR_CON_ON_OFF_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MOTOR_CON_ON_OFF_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  IO_EN_PORT,
		.pinPortIdx        =  IO_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IO_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  MII_RX_CLK_PORT,
		.pinPortIdx        =  MII_RX_CLK_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_HIGH_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
	},
	{
		.base              =  MII_RMII_TX_CLK_PORT,
		.pinPortIdx        =  MII_RMII_TX_CLK_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_HIGH_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
	},
	{
		.base              =  MII_RMII_TX_EN_PORT,
		.pinPortIdx        =  MII_RMII_TX_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_HIGH_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT5,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NULL,
		.digitalFilter     =  false,
	},
    {
		.base              =  VDD_MCU_EN_PORT,
		.pinPortIdx        =  VDD_MCU_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  VDD_MCU_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  IMU_IRQ_PORT,
		.pinPortIdx        =  IMU_IRQ_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_INT_FALLING_EDGE,
		.clearIntFlag      =  false,
		.gpioBase          =  IMU_IRQ_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  ON_OFF_MCU_PORT,
		.pinPortIdx        =  ON_OFF_MCU_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ON_OFF_MCU_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  LTE_SPI_IRQ_PORT,
		.pinPortIdx        =  LTE_SPI_IRQ_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LTE_SPI_IRQ_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  DBA_STB_N_PORT,
		.pinPortIdx        =  DBA_STB_N_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  DBA_STB_N_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  EXT_WDT_WDI_PORT,
		.pinPortIdx        =  EXT_WDT_WDI_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  EXT_WDT_WDI_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  EXT_WDT_EN_PORT,
		.pinPortIdx        =  EXT_WDT_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  EXT_WDT_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  ABS_EN_PORT,
		.pinPortIdx        =  ABS_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ABS_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  NBR_PLT_LED_EN_PORT,
		.pinPortIdx        =  NBR_PLT_LED_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  NBR_PLT_LED_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  MOTOR_CAN_ERR_PORT,
		.pinPortIdx        =  MOTOR_CAN_ERR_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MOTOR_CAN_ERR_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  MOTOR_STB_N_PORT,
		.pinPortIdx        =  MOTOR_STB_N_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MOTOR_STB_N_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    
    /* Port E block settings */
#ifdef USE_ETM_TRACE_DBG
    {
		.base              =  ETM_TRACE_D1_PORT,
		.pinPortIdx        =  ETM_TRACE_D1_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ETM_TRACE_D1_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	},
#endif
	{
		.base              =  RTC_SDA_PORT,
		.pinPortIdx        =  RTC_SDA_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT4,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  RTC_SDA_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  RTC_SCL_PORT,
		.pinPortIdx        =  RTC_SCL_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT4,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  RTC_SCL_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  IMX6_GPIO_01_PORT,
		.pinPortIdx        =  IMX6_GPIO_01_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX6_GPIO_01_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  IMX6_GP32_PORT,
		.pinPortIdx        =  IMX6_GP32_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX6_GP32_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  RIGHT_IND_PORT,
		.pinPortIdx        =  RIGHT_IND_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  RIGHT_IND_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  HEAD_LAMP_12V_EN_PORT,
		.pinPortIdx        =  HEAD_LAMP_12V_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  HEAD_LAMP_12V_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  LOW_BEAM_PORT,
		.pinPortIdx        =  LOW_BEAM_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LOW_BEAM_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  FWD_EN_PORT,
		.pinPortIdx        =  FWD_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  FWD_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  IMX6_GP34_PORT,
		.pinPortIdx        =  IMX6_GP34_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX6_GP34_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  LEFT_IND_PORT,
		.pinPortIdx        =  LEFT_IND_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LEFT_IND_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  LTE_MODULE_STATUS_PORT,
		.pinPortIdx        =  LTE_MODULE_STATUS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LTE_MODULE_STATUS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  MOTOR_CAN_EN_PORT,
		.pinPortIdx        =  MOTOR_CAN_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  MOTOR_CAN_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  IMU_VDD_EN_PORT,
		.pinPortIdx        =  IMU_VDD_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMU_VDD_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  IMX6_VDD_EN_PORT,
		.pinPortIdx        =  IMX6_VDD_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  IMX6_VDD_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
    {
		.base              =  ENET_SPI_SCK_PORT,
		.pinPortIdx        =  ENET_SPI_SCK_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_ALT3,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ENET_SPI_SCK_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
    {
		.base              =  VBAT_EN2_PORT,
		.pinPortIdx        =  VBAT_EN2_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  VBAT_EN2_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  ABS_LED_IS_PORT,
		.pinPortIdx        =  ABS_LED_IS_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  ABS_LED_IS_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_UNSPECIFIED_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  THROTTLE2_PORT,
		.pinPortIdx        =  THROTTLE2_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_NOT_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_PIN_DISABLED,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  THROTTLE2_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_UNSPECIFIED_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  LED_RED_PORT,
		.pinPortIdx        =  LED_RED_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LED_RED_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  LED_GREEN_PORT,
		.pinPortIdx        =  LED_GREEN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  LED_GREEN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  BMS_STB_N_PORT,
		.pinPortIdx        =  BMS_STB_N_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  BMS_STB_N_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  0U,
	},
	{
		.base              =  BMS_CAN_EN_PORT,
		.pinPortIdx        =  BMS_CAN_EN_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  BMS_CAN_EN_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_OUTPUT_DIRECTION,
		.initValue         =  1U,
	},
	{
		.base              =  BMS_CAN_ERR_PORT,
		.pinPortIdx        =  BMS_CAN_ERR_PIN,
		.pullConfig        =  PORT_INTERNAL_PULL_UP_ENABLED,
		.passiveFilter     =  false,
		.driveSelect       =  PORT_LOW_DRIVE_STRENGTH,
		.mux               =  PORT_MUX_AS_GPIO,
		.pinLock           =  false,
		.intConfig         =  PORT_DMA_INT_DISABLED,
		.clearIntFlag      =  false,
		.gpioBase          =  BMS_CAN_ERR_GPIO,
		.digitalFilter     =  false,
        .direction         =  GPIO_INPUT_DIRECTION,
		.initValue         =  1U,
	}
};

